apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - litellm.namespace.yaml
  - litellm.database.superuser.secret.yaml
  - litellm.database.user.secret.yaml
  - litellm.database.yaml
  - litellm.secret.yaml
  - litellm.config-map.yaml
  - litellm.deployment.yaml
  - litellm.service.yaml
  - litellm.ingress.yaml

