apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:6.10.0
          ports:
            - name: http
              containerPort: 2368
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /var/lib/ghost/content
              name: ghost-storage
              subPath: content
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "ghost-mariadb-cluster.ghost-system.svc.cluster.local"
            - name: database__connection__port
              value: "3306"
            - name: database__connection__user
              value: "ghost"
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-database-secret
                  key: mysql-password
            - name: database__connection__database
              value: "ghost"
            - name: url
              value: "https://tinyrack.net"
            - name: mail__from
              value: "noreply@tinyrack.net"
            - name: mail__transport
              value: "SMTP"
            - name: mail__options__host
              value: "mail.winetree94.com"
            - name: mail__options__port
              value: "465"
            - name: mail__options__secure
              value: "true"
            - name: mail__options__auth__user
              value: "noreply@tinyrack.net"
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: ghost-smtp-secret
                  key: smtp_password
      volumes:
        - name: ghost-storage
          persistentVolumeClaim:
            claimName: ghost-storage
