apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - ghost.yaml
  # - ghost-translate.yaml
  - memos.yaml
  - discourse.yaml
  # - authentik.yaml
  # - metamcp.yaml
  # - litellm.yaml
#  - openwebui.yaml
