apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - sealed-secrets.yaml
  - reflector.yaml
  - traefik.yaml
  - cert-manager.yaml
#  - cloudflared.yaml
#  - tailscale.yaml
  - configs.yaml
  - longhorn.yaml
  - mariadb-operator.yaml
  - cloudnative-pg.yaml
