apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ghost-translate-ingress-route
  namespace: ghost-translate-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cms.translate.tinyrack.net`)
      kind: Rule
      services:
        - name: ghost-translate-service
          port: 80
  tls:
    secretName: letsencrypt-wildcard-cert-tinyrack.net
