apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghost-translate.namespace.yaml
  - ghost-translate.database.secret.yaml
  - ghost-translate.smtp.secret.yaml
  - ghost-translate.initial-admin.secret.yaml
  - ghost-translate.database.yaml
  - ghost-translate.deployment.yaml
  - ghost-translate.service.yaml
  - ghost-translate.ingress-route.yaml