apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - discourse.namespace.yaml
  - discourse.database.superuser.secret.yaml
  - discourse.database.user.secret.yaml
  - discourse.smtp.secret.yaml
  - discourse.redis.secret.yaml
  - discourse.database-15.yaml
  - discourse.redis.yaml
  - discourse.deployment.yaml
  - discourse.service.yaml
  - discourse.ingress.yaml
